Update install-packages.sh

diff --git a/run_once_before_install-packages.sh.tmpl b/run_once_before_install-packages.sh.tmpl
--- a/run_once_before_install-packages.sh.tmpl
+++ b/run_once_before_install-packages.sh.tmpl
@@ -68,9 +68,10 @@ for package in "${PACKAGES[@]}"; do
     fi
 done
 
-# Install iTerm2
-echo "💻 Installing iTerm2..."
-brew install --cask iterm2 || echo "⚠️  iTerm2 may already be installed or failed to install"
+# Install Ghostty 👻
+echo "👻 Installing Ghostty..."
+brew install --cask ghostty || echo "⚠️  ghostty may already be installed or failed to install"
+
 
 # Install Nerd Fonts
 echo "🔤 Installing RobotoMono Nerd Font..."
